# Welcome to Jekyll!

# Website settings
title: "Massimo Quadrana's Webpage"
description: "Massimo's Webapage and blog"
keywords: "Quadrana,phd,PhD,blog,resume,papers"

baseurl: "/"
url: "http://mquad.github.io"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Massimo Quadrana'
  first_name: 'Massimo'
  last_name: 'Quadrana'
  email: 'massimo.quadrana@polimi.it'
  github_username: 'mquad'
  head_img: 'static/img/landing/max.jpg'

# landing page
landing:
  home: 'Home'
  about: 'About'
  career: 'Career'
  papers: 'Papers'
  contact: 'Link'

# blog index
# index:
#   home: 'Home'
#   python: 'Python'
#   linux: 'Linux'
#   html: 'HTML'
#   database: 'Database'
#   mac: 'Mac'
#   life: 'Life'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29

# blog img path
img_path: '/static/img/blog'

# Build settings
encoding: "utf-8"

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
